google_analytics:
theme: jekyll-theme-leap-day

logo: /assets/images/PanoMedium.png
title: N Scale Cleveland Flats
description: N Scale Layout Modeling the Cleveland Flats Industrial DIstrict in the 1970s
sidebar_image: /assets/images/PanoSmall2.png

show_downloads: false
