google_analytics:
theme: jekyll-theme-leap-day

logo: /assets/images/PanoMedium.png
title: N Scale Cleveland Flats
description: N Scale Layout Modeling the Cleveland Flats Industrial DIstrict in the 1970s
sidebar_image: /assets/images/NMRA_DIVISION3_MID_CENTRAL_REGION_revA_plain_darkGrayOffWhite.svg

show_downloads: false
